API_KEYS:
  Fred: "42744da44c4384863c27c4a384445205"

symbol_size: 100

articles:
  size: 10
  retry: 50

save_method:
  save_to_file: true
  save_to_DB: true

database:
  url: mysql+pymysql://root:363636@localhost:3306/crawling_db
  # url: mysql+pymysql://crawlingadmin:crawling05@msiwol.iptime.org:44005/crawling_db

color_log: true
