name: CrawlingObserverAPI_CD

on:
  # workflow_run:
  #   workflows: ["StockAnalysisAPI_CI"]
  #   types:
  #     - completed
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Github Repository'
        uses: actions/checkout@v2

      - name: 'Login and Copy project via SSH on Remote Server'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./*"
          target: "/home/stockmarketanalysis/dockers/CrawlingObserverAPI/service"

      - name: 'Install dependencies on the server'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # 서버에서 가상환경 생성 및 의존성 설치
            cd ~/dockers/CrawlingObserverAPI/service
            python3 -m venv venv  # 가상환경 생성 (이미 존재하는 경우 생략 가능)
            source venv/bin/activate  # 가상환경 활성화
            pip install --upgrade pip  # pip 최신 버전으로 업그레이드
            pip install -r requirements.txt  # 의존성 설치

      - name: 'Deploy docker via SSH on Remote Server'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Docker로 서비스 빌드 및 실행
            cd ~/dockers/CrawlingObserverAPI/service
            docker build -t docker:CrawlingObserverAPI_service .
            docker stop CrawlingObserverAPI_service || true
            docker rm CrawlingObserverAPI_service || true
            docker run -d --name CrawlingObserverAPI_service docker:CrawlingObserverAPI_service
