name: CrawlingObserverAPI_CD

on:
  # workflow_run:
  #   workflows: ["StockAnalysisAPI_CI"]
  #   types:
  #     - completed
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Github Repository'
        uses: actions/checkout@v2

      - name: 'Login and Deploy via SSH on Remote Server'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}  # 비밀번호로 로그인하도록 수정
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # 원격 서버에 배포 폴더가 없으면 생성
            mkdir -p ~/dockers/CrawlingObserverAPI/service
            # rsync로 프로젝트 파일 복사
            rsync -avz ./ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_ADDR }}:~/dockers/CrawlingObserverAPI/service
            # Docker로 서비스 빌드 및 실행
            cd ~/dockers/CrawlingObserverAPI/service
            docker build -t docker:CrawlingObserverAPI_service .
            docker stop CrawlingObserverAPI_service || true
            docker rm CrawlingObserverAPI_service || true
            docker run -d --name CrawlingObserverAPI_service docker:CrawlingObserverAPI_service
